### ISSUE TITLE
"target should be string" error when trying to migrate

### ISSUE THREAD

**Issue by pferrot** [Azure/iotc-migrator#3]
Got the error below when trying to migrate a basic test device from one IoT Central application to another:

```
The provided request body contains the following errors: target should be string.
You can contact support at https://aka.ms/iotcentral-support.
Please include the following information. Request ID: 1ch5htst, Time: Mon, 25 Apr 2022 07:37:47 GMT.
```

![image](https://user-images.githubusercontent.com/12295384/165042405-a5b5d081-aa60-47ba-b0f4-cf5f5d9c4337.png)

**Comment by pferrot** [comment]
I tried to force a string in the code (`'target': payload.template ? "true":"false",`, but then I got the error below, so it must be something a bit more tricky.

```
A specified target was not found.
You can contact support at https://aka.ms/iotcentral-support.
Please include the following information. Request ID: 5il7en18, Time: Mon, 25 Apr 2022 07:43:58 GMT.
```

**Comment by lucadruda** [comment]
new version available with several bug fixes.
